services:
  - type: web
    name: demobank
    runtime: docker
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MAVEN_VERSION
        value: 3.9.12
      - key: MONGODB_URI
        sync: false
